name: deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      - name: use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: npm
        run: |
          npm install
          npm run build:prod
        env:
          CI: true
      - name: Deploy     
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          REMOTE_HOST: 49.235.155.137
          REMOTE_USER: root
          SOURCE: product/
          TARGET: /data/sell
